### ISSUE TITLE
Angular 7 compatibility

### ISSUE THREAD

**Issue by marunp** [JR33D/ngx-chronology#2]
Short description explaining the high-level reason for the new issue.

Angular 7 gives build error.

## Current behavior
Build fails with Angular 7

## Expected behavior
Angular 7 project Builds

## Steps to replicate behavior (include URLs)

1. Add this component to Angular 7 project
2. Build the project

**Comment by JR33D** [comment]
Hey Thanks for the heads up about this issue. I haven't had a chance to look at this project recently but will work on putting and update out  to make it work with angular 7

**Comment by kashkashio** [comment]
Hi @JR33D 
I managed to fix your issue....

The reason it wont work in angular is the reason that you are using BrowserModule instead of CommonModule of angular inside your'e library.
fix it and it will be compatible.

**Comment by kashkashio** [comment]
this is how the file
chronology.module.ts should be

`import {NgModule} from '@angular/core';
import {FontAwesomeModule} from '@fortawesome/angular-fontawesome';
import {library} from '@fortawesome/fontawesome-svg-core';
import {fas} from '@fortawesome/free-solid-svg-icons';
import {far} from '@fortawesome/free-regular-svg-icons';
import {fab} from '@fortawesome/free-brands-svg-icons';

import {ChronologyComponent} from './chronology/chronology.component';
import {
    ChronologyContentDirective,
    ChronologyTitleDirective,
} from './directives/layout.directive';
import {CommonModule} from '@angular/common';
import {MatIconModule} from '@angular/material';

library.add(far, fas, fab);

@NgModule({
    imports: [CommonModule, FontAwesomeModule, MatIconModule],
    declarations: [
        ChronologyComponent,
        ChronologyContentDirective,
        ChronologyTitleDirective,
    ],
    exports: [
        ChronologyComponent,
        ChronologyTitleDirective,
        ChronologyContentDirective
    ],
})
export class NgxChronologyModule {
}`

**Comment by JR33D** [comment]
This has been fixed with PR #3
